version: '3'

services:
  running-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: running_app
    restart: always
    ports:
      - "4000:4000"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=running_fund sslmode=disable timezone=UTC connect_timeout=5"

  postgres:
    image: 'postgres:16.0'
    container_name: compose_postgres
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: running_fund
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
