version: '3'

services:
  running-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: running_app
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=poomipat password=running_fund_dev dbname=running_fund_dev sslmode=disable timezone=UTC connect_timeout=5"
      CRITERIA_VERSION: 1
    env_file:
      - .env

  postgres:
    image: 'postgres:16.0'
    container_name: compose_postgres
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: poomipat
      POSTGRES_PASSWORD: running_fund_dev
      POSTGRES_DB: running_fund_dev
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
